"""
Developer Endpoints
-------------------
GET  /api/v1/daily-summary      – fetch precomputed daily standup summary
GET  /api/v1/sprint-summary     – fetch precomputed sprint summary
POST /api/v1/search             – natural-language search over developer activity
GET  /api/v1/standup-helper     – LLM-powered standup: talking points, risks, blockers, pending items
GET  /api/v1/pending-attention  – DEPRECATED: use /standup-helper (pending_items field)
"""
from fastapi import APIRouter, Query
from fastapi.responses import JSONResponse

from app.schemas.developer import (
    DailySummaryResponse,
    PendingAttentionResponse,
    SearchRequest,
    SearchResponse,
    SprintSummaryResponse,
    StandupHelperResponse,
)
from app.services.developer_service import DeveloperService

router = APIRouter()
_svc = DeveloperService()


@router.get(
    "/daily-summary",
    response_model=DailySummaryResponse,
    summary="Get daily standup summary for a developer",
    description=(
        "Returns the most recently precomputed daily summary for the given developer. "
        "The summary is generated by a scheduled background job and is not computed on-demand."
    ),
)
async def get_daily_summary(
    userId: str = Query(..., description="Developer user ID"),
):
    return await _svc.get_daily_summary(user_id=userId)


@router.get(
    "/sprint-summary",
    response_model=SprintSummaryResponse,
    summary="Get sprint summary for a developer",
    description=(
        "Returns the precomputed sprint summary for the given developer and sprint. "
        "The summary covers all activity during the sprint."
    ),
)
async def get_sprint_summary(
    userId: str = Query(..., description="Developer user ID"),
    sprintId: str = Query(..., description="Sprint ID"),
):
    return await _svc.get_sprint_summary(user_id=userId, sprint_id=sprintId)


@router.post(
    "/search",
    response_model=SearchResponse,
    summary="Natural-language search over developer activity",
    description=(
        "Accepts a free-text question and returns a natural-language answer "
        "backed by structured and/or semantic retrieval over developer activity data."
    ),
)
async def search(body: SearchRequest):
    return await _svc.search(
        query=body.query,
        user_id=body.user_id,
        sprint_id=body.sprint_id,
        limit=body.limit,
    )


@router.get(
    "/standup-helper",
    response_model=StandupHelperResponse,
    summary="Get LLM-powered standup update for a developer",
    description=(
        "Fetches UserSprintContext from DynamoDB and recent activity chunks from OpenSearch, "
        "then uses Claude (Bedrock) to generate structured standup talking points, risks, "
        "blockers, and pending action items. "
        "The pending_items field replaces the deprecated /pending-attention endpoint."
    ),
)
async def get_standup_helper(
    userId: str = Query(..., description="Developer user ID"),
    sprintId: str = Query(..., description="Sprint ID"),
):
    return await _svc.get_standup_helper(user_id=userId, sprint_id=sprintId)


@router.get(
    "/pending-attention",
    response_model=PendingAttentionResponse,
    deprecated=True,
    summary="[DEPRECATED] Get items needing developer attention",
    description=(
        "DEPRECATED — use GET /standup-helper instead. "
        "The standup-helper response now includes a `pending_items` field that contains "
        "LLM-generated action items sourced from both DynamoDB and OpenSearch. "
        "This endpoint returns the raw pre-computed pending_attention list from DynamoDB "
        "without any LLM enrichment."
    ),
)
async def get_pending_attention(
    userId: str = Query(..., description="Developer user ID"),
    sprintId: str = Query(..., description="Sprint ID"),
):
    return await _svc.get_pending_attention(user_id=userId, sprint_id=sprintId)
