"""
Developer Endpoints
-------------------
GET  /api/v1/daily-summary          – fetch precomputed daily standup summary
GET  /api/v1/sprint-summary         – fetch precomputed sprint summary
POST /api/v1/search                 – natural-language search over developer activity
"""
from fastapi import APIRouter, Query

from app.schemas.developer import (
    DailySummaryResponse,
    SearchRequest,
    SearchResponse,
    SprintSummaryResponse,
)
from app.services.developer_service import DeveloperService

router = APIRouter()
_svc = DeveloperService()


@router.get(
    "/daily-summary",
    response_model=DailySummaryResponse,
    summary="Get daily standup summary for a developer",
    description=(
        "Returns the most recently precomputed daily summary for the given developer. "
        "The summary is generated by a scheduled background job and is not computed "
        "on-demand."
    ),
)
async def get_daily_summary(
    userId: str = Query(..., description="Developer user ID"),
):
    return await _svc.get_daily_summary(user_id=userId)


@router.get(
    "/sprint-summary",
    response_model=SprintSummaryResponse,
    summary="Get sprint summary for a developer",
    description=(
        "Returns the precomputed sprint summary for the given developer and sprint. "
        "The summary covers all activity during the sprint."
    ),
)
async def get_sprint_summary(
    userId: str = Query(..., description="Developer user ID"),
    sprintId: str = Query(..., description="Sprint ID"),
):
    return await _svc.get_sprint_summary(user_id=userId, sprint_id=sprintId)


@router.post(
    "/search",
    response_model=SearchResponse,
    summary="Natural-language search over developer activity",
    description=(
        "Accepts a free-text question and returns a natural-language answer "
        "backed by structured and/or semantic retrieval over developer activity data."
    ),
)
async def search(body: SearchRequest):
    return await _svc.search(
        query=body.query,
        user_id=body.user_id,
        sprint_id=body.sprint_id,
        limit=body.limit,
    )
